#H2 Db config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.usernam=sa
spring.datasource.password=

#JPA hibernate configuration

spring.jap.database-platform=org.hibernate.dialect.H2Dialect
spring.jap.hibernate.ddl-auto-create-drop
spring.h2.console.enabled=true